title: Estere Docs
description: Documentazione ufficiale di Estere — il software che legge le fatture estere e crea l'autofattura su Fatture in Cloud.
baseurl: "/fattureestere"
url: "https://danewebbb.github.io"

repository: danewebbb/fattureestere

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
